version: v0.7
superbench:
  enable:
  # - ib-traffic:pair_wise
  # - nccl-bw:all_nodes
  monitor:
    enable: true
    sample_duration: 1
    sample_interval: 10
  var:
    nccl_env: &nccl_env
      NCCL_IB_PCI_RELAXED_ORDERING: '1'
      NCCL_NET_GDR_LEVEL: '5'
      NCCL_TOPO_FILE: /opt/microsoft/ndv4-topo.xml
      NCCL_DEBUG: WARN
    nccl_all_nodes_pattern: &nccl_all_nodes_pattern
      type: all-nodes
      mpi_pattern: true
    nccl_pair_wise_pattern: &nccl_pair_wise_pattern
      type: pair-wise
      mpi_pattern: true
    nccl_k_batch_pattern: &nccl_k_batch_pattern
      type: k-batch
      mpi_pattern: true
      batch: 3
    nccl_topo-aware_pattern: &nccl_topo_aware_pattern
      type: topo-aware
      mpi_pattern: true
      ibnetdiscover: /tmp
      min_dist: 2
      max_dist: 6
    nccl_allreduce_config: &nccl_allreduce_config
      timeout: 1200
      modes:
      - name: mpi
        proc_num: 8
        node_num: all
        pattern:
          <<: *nccl_all_nodes_pattern
        env:
          <<: *nccl_env
      parameters:
        minbytes: 1K
        maxbytes: 8G
        stepfactor: 2
        check: 1
        warmup_iters: 20
        iters: 100
  benchmarks:
    ib-traffic:pair-wise:
      modes:
      - name: mpi
        proc_num: 8
        node_num: all
        mca:
          routed: direct
      parameters:
        msg_size: 8388608
        bidirectional: yes
        ib_dev: mlx5_ib$LOCAL_RANK
        gpu_dev: $LOCAL_RANK
        numa_dev: $((LOCAL_RANK/2))
    nccl-bw:all_nodes:
      <<: *nccl_allreduce_config
    nccl-bw:pair_wise:
      <<: *nccl_allreduce_config
    nccl-bw:k_batch:
      <<: *nccl_allreduce_config
    nccl-bw:topo_aware:
      <<: *nccl_allreduce_config
